/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import menuPanel.menuLapharian;

/**
 *
 * @author user
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_barang = new javax.swing.JPanel();
        pn_klik = new javax.swing.JPanel();
        icon_barang = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn_dashboard1 = new javax.swing.JPanel();
        pn_klik1 = new javax.swing.JPanel();
        icon_dashboard = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_transaksi = new javax.swing.JPanel();
        pn_klik2 = new javax.swing.JPanel();
        icon_transaksi = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pn_lapharian = new javax.swing.JPanel();
        pn_klik3 = new javax.swing.JPanel();
        icon_lapharian = new javax.swing.JLabel();
        btn_lapHarian = new javax.swing.JLabel();
        pn_lappengeluaran = new javax.swing.JPanel();
        pn_klik4 = new javax.swing.JPanel();
        icon_lappengeluaran = new javax.swing.JLabel();
        btn_lappengeluaran = new javax.swing.JLabel();
        pn_lapbulanan = new javax.swing.JPanel();
        pn_klik5 = new javax.swing.JPanel();
        icon_lapbulanan = new javax.swing.JLabel();
        btn_lapbulanan = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pn_akun = new javax.swing.JPanel();
        pn_klik6 = new javax.swing.JPanel();
        icon_akun = new javax.swing.JLabel();
        btn_akun = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_isi = new javax.swing.JPanel();
        pn_konten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(51, 255, 51));
        pn_kiri.setPreferredSize(new java.awt.Dimension(250, 720));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Sahabat Tani");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\icon tani.png")); // NOI18N
        jLabel2.setText("jLabel2");

        pn_barang.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik.setPreferredSize(new java.awt.Dimension(5, 32));

        javax.swing.GroupLayout pn_klikLayout = new javax.swing.GroupLayout(pn_klik);
        pn_klik.setLayout(pn_klikLayout);
        pn_klikLayout.setHorizontalGroup(
            pn_klikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klikLayout.setVerticalGroup(
            pn_klikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        icon_barang.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\boxes_5626394.png")); // NOI18N
        icon_barang.setText("jLabel4");

        btn_barang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_barang.setText("Barang");
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barangMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pn_barangLayout = new javax.swing.GroupLayout(pn_barang);
        pn_barang.setLayout(pn_barangLayout);
        pn_barangLayout.setHorizontalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_barangLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_barangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_barangLayout.setVerticalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_barang)
                    .addComponent(btn_barang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("TRANSAKSI");

        pn_dashboard1.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_klik1Layout = new javax.swing.GroupLayout(pn_klik1);
        pn_klik1.setLayout(pn_klik1Layout);
        pn_klik1Layout.setHorizontalGroup(
            pn_klik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_klik1Layout.setVerticalGroup(
            pn_klik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        icon_dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\dashboard_2328909.png")); // NOI18N
        icon_dashboard.setText("jLabel4");

        btn_dashboard.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_dashboard1Layout = new javax.swing.GroupLayout(pn_dashboard1);
        pn_dashboard1.setLayout(pn_dashboard1Layout);
        pn_dashboard1Layout.setHorizontalGroup(
            pn_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboard1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_dashboard1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        pn_dashboard1Layout.setVerticalGroup(
            pn_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_dashboard)
                    .addComponent(btn_dashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_dashboard1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Barang");

        pn_transaksi.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik2.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik2.setPreferredSize(new java.awt.Dimension(5, 32));

        javax.swing.GroupLayout pn_klik2Layout = new javax.swing.GroupLayout(pn_klik2);
        pn_klik2.setLayout(pn_klik2Layout);
        pn_klik2Layout.setHorizontalGroup(
            pn_klik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klik2Layout.setVerticalGroup(
            pn_klik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        icon_transaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\sales_2155879.png")); // NOI18N
        icon_transaksi.setText("jLabel4");

        btn_transaksi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_transaksi.setText("Transaksi");
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pn_transaksiLayout = new javax.swing.GroupLayout(pn_transaksi);
        pn_transaksi.setLayout(pn_transaksiLayout);
        pn_transaksiLayout.setHorizontalGroup(
            pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_transaksiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_transaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_transaksiLayout.setVerticalGroup(
            pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_transaksi)
                    .addComponent(btn_transaksi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_transaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Laporan");

        pn_lapharian.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik3.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik3.setPreferredSize(new java.awt.Dimension(5, 32));

        javax.swing.GroupLayout pn_klik3Layout = new javax.swing.GroupLayout(pn_klik3);
        pn_klik3.setLayout(pn_klik3Layout);
        pn_klik3Layout.setHorizontalGroup(
            pn_klik3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klik3Layout.setVerticalGroup(
            pn_klik3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        icon_lapharian.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\laporan icon.png")); // NOI18N
        icon_lapharian.setText("jLabel4");

        btn_lapHarian.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_lapHarian.setText("Harian");
        btn_lapHarian.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                btn_lapHarianAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        btn_lapHarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lapHarianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lapHarianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lapHarianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_lapharianLayout = new javax.swing.GroupLayout(pn_lapharian);
        pn_lapharian.setLayout(pn_lapharianLayout);
        pn_lapharianLayout.setHorizontalGroup(
            pn_lapharianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lapharianLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_lapharian, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lapHarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_lapharianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_lapharianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_lapharianLayout.setVerticalGroup(
            pn_lapharianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lapharianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_lapharianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_lapharian)
                    .addComponent(btn_lapHarian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_lapharianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lapharianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pn_lappengeluaran.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik4.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik4.setPreferredSize(new java.awt.Dimension(5, 33));

        javax.swing.GroupLayout pn_klik4Layout = new javax.swing.GroupLayout(pn_klik4);
        pn_klik4.setLayout(pn_klik4Layout);
        pn_klik4Layout.setHorizontalGroup(
            pn_klik4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klik4Layout.setVerticalGroup(
            pn_klik4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        icon_lappengeluaran.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\laporan icon.png")); // NOI18N
        icon_lappengeluaran.setText("jLabel4");

        btn_lappengeluaran.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_lappengeluaran.setText("Pengeluaran");
        btn_lappengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lappengeluaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lappengeluaranMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_lappengeluaranLayout = new javax.swing.GroupLayout(pn_lappengeluaran);
        pn_lappengeluaran.setLayout(pn_lappengeluaranLayout);
        pn_lappengeluaranLayout.setHorizontalGroup(
            pn_lappengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lappengeluaranLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_lappengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lappengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_lappengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_lappengeluaranLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_lappengeluaranLayout.setVerticalGroup(
            pn_lappengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lappengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_lappengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_lappengeluaran)
                    .addComponent(btn_lappengeluaran))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_lappengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_lappengeluaranLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_lapbulanan.setBackground(new java.awt.Color(255, 255, 255));

        pn_klik5.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik5.setPreferredSize(new java.awt.Dimension(5, 33));

        javax.swing.GroupLayout pn_klik5Layout = new javax.swing.GroupLayout(pn_klik5);
        pn_klik5.setLayout(pn_klik5Layout);
        pn_klik5Layout.setHorizontalGroup(
            pn_klik5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klik5Layout.setVerticalGroup(
            pn_klik5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        icon_lapbulanan.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\laporan icon.png")); // NOI18N
        icon_lapbulanan.setText("jLabel4");

        btn_lapbulanan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_lapbulanan.setText("Bulanan");
        btn_lapbulanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lapbulananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lapbulananMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_lapbulananLayout = new javax.swing.GroupLayout(pn_lapbulanan);
        pn_lapbulanan.setLayout(pn_lapbulananLayout);
        pn_lapbulananLayout.setHorizontalGroup(
            pn_lapbulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lapbulananLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_lapbulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lapbulanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_lapbulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_lapbulananLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_lapbulananLayout.setVerticalGroup(
            pn_lapbulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lapbulananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_lapbulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_lapbulanan)
                    .addComponent(btn_lapbulanan))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(pn_lapbulananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_lapbulananLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("Akun");

        pn_klik6.setBackground(new java.awt.Color(255, 255, 255));
        pn_klik6.setPreferredSize(new java.awt.Dimension(5, 32));

        javax.swing.GroupLayout pn_klik6Layout = new javax.swing.GroupLayout(pn_klik6);
        pn_klik6.setLayout(pn_klik6Layout);
        pn_klik6Layout.setHorizontalGroup(
            pn_klik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_klik6Layout.setVerticalGroup(
            pn_klik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        icon_akun.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\person_13924070.png")); // NOI18N
        icon_akun.setText("jLabel4");

        btn_akun.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_akun.setText("Akun");

        javax.swing.GroupLayout pn_akunLayout = new javax.swing.GroupLayout(pn_akun);
        pn_akun.setLayout(pn_akunLayout);
        pn_akunLayout.setHorizontalGroup(
            pn_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_akunLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_akunLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        pn_akunLayout.setVerticalGroup(
            pn_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_akunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_akun)
                    .addComponent(btn_akun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_akunLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_klik6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pn_akun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_lapbulanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_lapharian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(pn_transaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_lappengeluaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_lapharian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_lappengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_lapbulanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_akun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_isi.setBackground(new java.awt.Color(250, 250, 250));

        pn_konten.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_isiLayout = new javax.swing.GroupLayout(pn_isi);
        pn_isi.setLayout(pn_isiLayout);
        pn_isiLayout.setHorizontalGroup(
            pn_isiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_isiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_konten, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_isiLayout.setVerticalGroup(
            pn_isiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_isiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_konten, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pn_kanan.add(pn_isi, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        pn_dashboard1.setBackground(new Color(240,240,240));
        pn_klik1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
         pn_dashboard1.setBackground(new Color(250,250,250));
        pn_klik1.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_lapHarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lapHarianMouseClicked
        pn_lapharian.setBackground(new Color(240,240,240));
        pn_klik3.setBackground(new Color(0,0,0));
        //untuk memangill panel laporan harian
        pn_konten.removeAll();
        pn_konten.add(new menuLapharian());
        pn_konten.repaint();
        pn_konten.revalidate(); 
    }//GEN-LAST:event_btn_lapHarianMouseClicked

    private void btn_lapHarianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lapHarianMouseEntered
        pn_lapharian.setBackground(new Color(240,240,240));
        pn_klik3.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_lapHarianMouseEntered

    private void btn_lapHarianAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_btn_lapHarianAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lapHarianAncestorMoved

    private void btn_lapHarianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lapHarianMouseExited
        pn_lapharian.setBackground(new Color(250,250,250));
        pn_klik3.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_btn_lapHarianMouseExited

    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        pn_transaksi.setBackground(new Color(240,240,240));
        pn_klik2.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseEntered
        pn_barang.setBackground(new Color(240,240,240));
        pn_klik.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_barangMouseEntered

    private void btn_lappengeluaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lappengeluaranMouseEntered
        pn_lappengeluaran.setBackground(new Color(240,240,240));
        pn_klik4.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_lappengeluaranMouseEntered

    private void btn_lappengeluaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lappengeluaranMouseExited
        pn_lappengeluaran.setBackground(new Color(250,250,250));
        pn_klik4.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_btn_lappengeluaranMouseExited

    private void btn_lapbulananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lapbulananMouseEntered
        pn_lapbulanan.setBackground(new Color(240,240,240));
        pn_klik5.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_lapbulananMouseEntered

    private void btn_lapbulananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lapbulananMouseExited
        pn_lapbulanan.setBackground(new Color(250,250,250));
        pn_klik5.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_btn_lapbulananMouseExited

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        pn_transaksi.setBackground(new Color(240,240,240));
        pn_klik2.setBackground(new Color(0,0,0));
        //
        pn_konten.removeAll();
        pn_konten.add(new transaksi());
        pn_konten.repaint();
        pn_konten.revalidate();
    }//GEN-LAST:event_btn_transaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_akun;
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_lapHarian;
    private javax.swing.JLabel btn_lapbulanan;
    private javax.swing.JLabel btn_lappengeluaran;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel icon_akun;
    private javax.swing.JLabel icon_barang;
    private javax.swing.JLabel icon_dashboard;
    private javax.swing.JLabel icon_lapbulanan;
    private javax.swing.JLabel icon_lapharian;
    private javax.swing.JLabel icon_lappengeluaran;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pn_akun;
    private javax.swing.JPanel pn_barang;
    private javax.swing.JPanel pn_dashboard1;
    private javax.swing.JPanel pn_isi;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_klik;
    private javax.swing.JPanel pn_klik1;
    private javax.swing.JPanel pn_klik2;
    private javax.swing.JPanel pn_klik3;
    private javax.swing.JPanel pn_klik4;
    private javax.swing.JPanel pn_klik5;
    private javax.swing.JPanel pn_klik6;
    private javax.swing.JPanel pn_konten;
    private javax.swing.JPanel pn_lapbulanan;
    private javax.swing.JPanel pn_lapharian;
    private javax.swing.JPanel pn_lappengeluaran;
    private javax.swing.JPanel pn_transaksi;
    // End of variables declaration//GEN-END:variables
}
